"1.7":
  K8S_VERSION: "1.24"
  JUJU_VERSION: "2.9"
  JUJU_VERSION_WITH_PATCH: "2.9.49"
  UATS_BRANCH: "track/1.7"
"1.8":
  K8S_VERSION: "1.29"
  JUJU_VERSION: "3.5"
  JUJU_VERSION_WITH_PATCH: "3.5.0"
  UATS_BRANCH: "main"
latest:
  K8S_VERSION: "1.29"
  JUJU_VERSION: "3.5"
  JUJU_VERSION_WITH_PATCH: "3.5.0"
  UATS_BRANCH: "main"
