"1.8":
  K8S_VERSION: "1.29"
  JUJU_VERSION: "3.4"
  UATS_BRANCH: "track/1.8"
"1.9":
  K8S_VERSION: "1.29"
  JUJU_VERSION: "3.6"
  UATS_BRANCH: "main"
latest:
  K8S_VERSION: "1.29"
  JUJU_VERSION: "3.6"
  UATS_BRANCH: "main"
