name: Task
description: File an enhancement proposal
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this enhancement
        proposal! Before submitting your issue, please make sure there
        isn't already a prior issue concerning this. If there is,
        please join that discussion instead.
  - type: textarea
    id: enhancement-proposal-context
    attributes:
      label: Context
      description: >
        Describe why we should work on this task/enhancement, as well as
        existing context we should be aware of
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal-what
    attributes:
      label: What needs to get done
      description: >
        Describe what needs to get done
      placeholder: |
        1. Look into X
        2. Implement Y
        3. Create file Z
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal-dod
    attributes:
      label: Definition of Done
      description: >
        What are the requirements for the task to be considered done
      placeholder: |
        1. We know how X works (spike)
        2. Code is doing Y
        3. Charm has functionality Z
    validations:
      required: true
