name: Task
description: File an enhancement proposal
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this enhancement
        proposal! Before submitting your issue, please make sure there
        isn't already a prior issue concerning this. If there is,
        please join that discussion instead.
  - type: textarea
    id: enhancement-proposal-why
    attributes:
      label: Why it needs to get done
      description: >
        Describe why it needs to get done
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal-what
    attributes:
      label: What needs to get done
      description: >
        Describe what needs to get done
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal-dod
    attributes:
      label: When is the task considered done
      description: >
        Describe what are the requirements for the task to be considered done
    validations:
      required: true
