apiVersion: "machinelearning.seldon.io/v1alpha2"
kind: "SeldonDeployment"
metadata:
  labels:
    app: "seldon"
  name: mock-classifier
spec:
  annotations:
    deployment_version: "v1"
    project_name: mock-classifier
  name: mock-classifier
  predictors:
    - annotations:
        predictor_version: "v1"
      componentSpecs:
        - spec:
            containers:
              - image: "seldonio/mock_classifier:1.0"
                imagePullPolicy: IfNotPresent
                name: mock-classifier
            terminationGracePeriodSeconds: 1
      graph:
        children: []
        name: mock-classifier
        type: "MODEL"
      name: mock-classifier
      replicas: 1
