name: Delete unattached (available) EBS volumes in all AWS regions
on:
  workflow_dispatch: # This event allows manual triggering from the Github UI
    secrets:
      BUNDLE_KUBEFLOW_EKS_AWS_ACCESS_KEY_ID:
        required: true
      BUNDLE_KUBEFLOW_EKS_AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  delete-volumes:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BUNDLE_KUBEFLOW_EKS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUNDLE_KUBEFLOW_EKS_AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region eu-central-1

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Run delete volumes script
        run: python scripts/delete_volumes.py