name: Tests

on:
  pull_request:

jobs:
  test-bundle-1_6-stable:
    runs-on: [self-hosted, linux, X64, xlarge]
    steps:
      - uses: actions/checkout@v3
      - name: Parse and enable DNS server
        run: |
          dns_server=$(grep -oPm1 'Current DNS Server: \K[^\s]+' <<< "$(resolvectl status)")
          echo $dns_server
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@1.1.0
        with:
          provider: microk8s
          channel: 1.24/stable
          charmcraft-channel: latest/candidate
          bootstrap-options: '--agent-version="2.9.42"'
          microk8s-addons: "storage dns:$dns_server rbac registry"

      - name: Configure kubectl
        run: |
          sg microk8s -c "microk8s config > ~/.kube/config"
      - run: |
          sg microk8s -c "microk8s enable metallb:'10.64.140.43-10.64.140.49,192.168.0.105-192.168.0.111'"
      - run: |
          sg microk8s -c "juju add-model kubeflow --config default-series=focal"
      - run: |
          sg microk8s -c "tox -e test_bundle_1.6 --recreate -- --model kubeflow --channel 1.6/stable"
