name: Tests

on:
 pull_request:
 

jobs:
 test-self-hosted-large-container:
   runs-on: [self-hosted, linux, X64, large]
   steps:
     - uses: actions/checkout@v3
     - run: curl https://www.google.com.au
 test-self-hosted-xlarge:
   runs-on: [self-hosted, linux, X64, xlarge]
   steps:
     - uses: actions/checkout@v3
     - run: echo hi
 test-self-hosted-two-xlarge:
   runs-on: [self-hosted, linux, X64, two-xlarge]
   steps:
     - uses: actions/checkout@v3
     - run: echo hi
