name: Publish bundle to CharmHub
on:
  workflow_call:
    inputs:
      release:
        description: Bundle release to run tests on and publish to Charmhub
        type: string
        required: true
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true
  workflow_dispatch:
    inputs:
      release:
        description: Bundle release to run tests on and publish to Charmhub (i.e. 1.10/stable
        type: string
        required: true
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true

jobs:
  publish-bundle-for-releases-affected:
    name: Publish bundle
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Publish bundle release ${{ inputs.release }}
        uses: canonical/charming-actions/upload-bundle@2.6.3
        with:
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bundle-path: releases/${{ inputs.release }}/
          channel: ${{ inputs.release }}
