name: Publish bundle to charm store

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish bundle
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo snap install charm --classic
        sudo snap install juju-helpers --classic --channel edge

    - name: Publish bundle
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
      run: |
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies
        juju-bundle publish --url cs:~kubeflow-charmers/kubeflow --serial --prune
