name: Report vulnerability issues via Github
on:
  workflow_call:
    inputs:
      issue-title:
        description: The title of the issue to be created/edited
        required: true
        type: string
      issue-body-file:
        description: The body of the issue to be created/edited
        required: true
        type: string
      issue-labels:
        description: A comma separated list of labels
        required: false
        type: string
        default: "bug"
    secrets: inherit

jobs:
  report-vulns:
    name: Create or edit issues for reporting vulnerabilities
    runs-on: ubuntu-22.04
    steps:
      - name: Get issue number if exists
        id: get-issue-number
        run: |
          export GH_TOKEN=${{ secrets.github-token }}
          export GITHUB_TOKEN=${{ secrets.github-token }}
          EXPECTED_TITLE="Vulnerabilities found for ${{ matrix.image }}"
          ISSUE_NUMBER=$(gh issue list --repo $GITHUB_REPOSITORY --limit 500 --json "number,title" | jq -r --arg expected_title "$EXPECTED_TITLE" '.[] | select(.title == $expected_title) | .number')
          echo "issue-number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Issue body
        id: issue-body
        run: |
          echo "## ${{ inputs.issue-title }}" > issue.md
          echo "" >> issue.md
          echo "\`\`\`" >> issue.md
          cat ${{ inputs.issue-body-file }} >> issue.md
          echo "\`\`\`" >> issue.md
          echo "" >> issue.md
          echo -e "\nDetails: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> issue.md
          echo "issue-body-file=issue.md" >> "$GITHUB_OUTPUT"

      - name: Report failures via Github issue
        run: |
          export GH_TOKEN=${{ secrets.github-token }}
          export GITHUB_TOKEN=${{ secrets.github-token }}
          if [ -z ${{ steps.get-issue-number.outputs.issue-number }} ]; then
            echo "---- Creating issue ----"
            gh issue create --repo $GITHUB_REPOSITORY \
            --title "${{ inputs.issue-title }}" \
            --label "${{ inputs.issue-labels }}" \
            --body-file "${{ steps.issue-body.outputs.issue-body-file }}"
          else
            echo "---- Editing issue ${{ steps.get-issue-number.outputs.issue-number }}----"
            gh issue edit --repo $GITHUB_REPOSITORY ${{ steps.get-issue-number.outputs.issue-number }} \
            --title "${{ inputs.issue-title }}" \
            --body-file "${{ steps.issue-body.outputs.issue-body-file }}"
          fi
