name: Tests

on:
  pull_request:

jobs:
  test-selenium:
    runs-on: [self-hosted, linux, X64, large]
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq python3-pip
          sudo --preserve-env=http_proxy,https_proxy,no_proxy pip3 install tox
          sudo snap install firefox
          whereis firefox

      - run: |

          mkdir ~/bin
          cd ~/bin
          ln -s /snap/bin/firefox.geckodriver geckodriver

      - run: |
          mkdir ~/tmp
          export TMPDIR="~/tmp"
          tox -e test_bundle_1.7 --recreate
