name: Tests

on:
  pull_request:

jobs:
  test-selenium:
    runs-on: [self-hosted, linux, X64, large]
    steps:
      - uses: actions/checkout@v3
      - run: |
          export XDG_RUNTIME_DIR="/run/user/$(id -u)"
          export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
          loginctl enable-linger USER
          sudo apt-get install dbus-user-session -yqq
          systemctl --user start dbus.service

      - name: Install tools
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq python3-pip
          sudo --preserve-env=http_proxy,https_proxy,no_proxy pip3 install tox
          sudo snap install firefox

      - run: |
          mkdir ~/bin
          ln -s /snap/bin/firefox.geckodriver ~/bin/geckodriver
          ~/bin/geckodriver --version

      - run: |
          tox -e test_bundle_1.7 --recreate
